"""Writer: render a ProjectModel into the .agent/ artifact tree.

Produces:
  .agent/architecture.md
  .agent/glossary.md
  .agent/constraints.md
  .agent/decisions.md
  .agent/modules/<module>.md
  .agent/flows/<flow>.flow.md
  .agent/entities.json
  .agent/causal-graph.json
  .agent/index.json          (manifest + provenance)
  .agent/tasks/              (created on demand by task-hardening)
"""
from __future__ import annotations

import datetime as _dt
import json
import re
from pathlib import Path

from . import __version__
from .analyzer import blast_radius
from .model import ProjectModel


def _slug(text: str) -> str:
    s = re.sub(r"[^\w\-]+", "-", text.strip().lower()).strip("-")
    return s or "item"


def _w(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _now() -> str:
    return _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def _header(title: str, model: ProjectModel) -> str:
    return (f"# {title}\n\n"
            f"> Generated by project-hardness v{model.engine_version or __version__} "
            f"on {model.generated_at}.\n"
            f"> Source-backed causal layer. Confidence labels: "
            f"EXTRACTED (parsed), INFERRED (heuristic), AMBIGUOUS, UNVERIFIED.\n"
            f"> Do not edit by hand — regenerate with "
            f"`python scripts/wiki.py hardness scan <project>`.\n\n")


def _architecture_md(model: ProjectModel) -> str:
    out = [_header(f"Architecture — {model.name}", model)]
    out.append(f"{model.summary}\n")
    out.append("## Languages & Frameworks\n")
    out.append(f"- Primary languages: {', '.join(model.primary_languages) or 'unknown'}")
    out.append(f"- Frameworks: {', '.join(model.frameworks) or 'none detected'}\n")
    out.append("## Modules\n")
    out.append("| Module | Kind | Responsibility | Depends on | Depended by |")
    out.append("| --- | --- | --- | --- | --- |")
    for m in model.modules:
        dep = ", ".join(m.depends_on[:6]) or "—"
        rdep = ", ".join(m.depended_by[:6]) or "—"
        out.append(f"| `{m.name}` | {m.kind} | {m.responsibility} | {dep} | {rdep} |")
    out.append("\n## Dependency Hotspots (highest blast radius)\n")
    ranked = sorted(model.modules, key=lambda m: len(m.depended_by), reverse=True)[:8]
    for m in ranked:
        if not m.depended_by:
            continue
        br = blast_radius(model, m.name)
        out.append(f"- `{m.name}` — {br['impacted_total']} modules impacted if changed; "
                   f"tests: {', '.join(br['related_tests']) or 'none detected'}")
    out.append("\nSee `modules/*.md` for per-module detail and `causal-graph.json` for the full graph.\n")
    return "\n".join(out)


def _glossary_md(model: ProjectModel) -> str:
    out = [_header(f"Glossary — {model.name}", model)]
    if not model.glossary:
        out.append("_No terms inferred yet._\n")
    for term, definition in model.glossary.items():
        out.append(f"- **{term}** — {definition}")
    return "\n".join(out) + "\n"


def _constraints_md(model: ProjectModel) -> str:
    out = [_header(f"Constraints & Do-Not-Modify Boundaries — {model.name}", model)]
    out.append("Respect these before editing. `block` = do not change without explicit "
               "user approval; `warn` = change with caution; `note` = be aware.\n")
    if not model.constraints:
        out.append("_No hard constraints auto-detected. Still verify lockfiles, generated "
                   "files, and applied migrations before editing._\n")
    by_sev = {"block": [], "warn": [], "note": []}
    for c in model.constraints:
        by_sev.setdefault(c.severity, []).append(c)
    for sev in ("block", "warn", "note"):
        items = by_sev.get(sev) or []
        if not items:
            continue
        out.append(f"## {sev.upper()}\n")
        for c in items:
            out.append(f"- **{c.rule}**")
            out.append(f"  - scope: `{c.scope}`")
            if c.reason:
                out.append(f"  - reason: {c.reason}")
            out.append(f"  - source: {c.source}")
    return "\n".join(out) + "\n"


def _decisions_md(model: ProjectModel) -> str:
    out = [_header(f"Historical Decisions — {model.name}", model)]
    out.append("Decision-flavored history extracted from git log. Append new decisions "
               "below the marker; regeneration preserves manual additions.\n")
    if not model.decisions:
        out.append("_No decision-flavored commits detected (or not a git repo)._\n")
    for d in model.decisions:
        out.append(f"## {d.title}")
        out.append(f"- date: {d.date or 'unknown'}  ·  source: {d.source}")
        if d.rationale:
            out.append(f"- rationale: {d.rationale}")
        out.append("")
    out.append("\n<!-- HARDNESS:MANUAL-DECISIONS-BELOW (preserved across regeneration) -->\n")
    return "\n".join(out)


def _module_md(model: ProjectModel, m) -> str:
    out = [_header(f"Module — {m.name}", model)]
    out.append(f"- **Kind**: {m.kind}")
    out.append(f"- **Responsibility**: {m.responsibility} _(confidence: {m.confidence})_")
    out.append(f"- **Languages**: {', '.join(m.languages) or 'n/a'}")
    out.append(f"- **Lines of code (approx)**: {m.loc}")
    out.append(f"- **Depends on**: {', '.join(f'`{d}`' for d in m.depends_on) or '—'}")
    out.append(f"- **Depended by**: {', '.join(f'`{d}`' for d in m.depended_by) or '—'}")
    out.append(f"- **External deps**: {', '.join(m.external_deps) or '—'}")
    if m.public_symbols:
        out.append(f"- **Public symbols**: {', '.join(f'`{s}`' for s in m.public_symbols)}")
    br = blast_radius(model, m.name)
    out.append(f"\n### Blast radius\n")
    out.append(f"Changing this module impacts ~{br['impacted_total']} module(s).")
    out.append(f"- Direct dependents: {', '.join(br['direct_dependents']) or 'none'}")
    out.append(f"- Transitive dependents: {', '.join(br['transitive_dependents']) or 'none'}")
    out.append(f"- Tests to run: {', '.join(br['related_tests']) or 'none auto-detected'}")
    out.append(f"\n### Files ({len(m.files)})\n")
    for f in m.files[:40]:
        out.append(f"- `{f}`")
    if len(m.files) > 40:
        out.append(f"- ...and {len(m.files) - 40} more")
    return "\n".join(out) + "\n"


def _flow_md(model: ProjectModel, flow) -> str:
    out = [_header(f"Flow — {flow.name}", model)]
    out.append(f"- **Trigger**: {flow.trigger}")
    out.append(f"- **Modules**: {', '.join(f'`{m}`' for m in flow.modules) or '—'}")
    out.append(f"- **Entities**: {', '.join(flow.entities) or '—'}")
    out.append(f"- **Confidence**: {flow.confidence}\n")
    out.append("### Steps\n")
    for i, step in enumerate(flow.steps, 1):
        out.append(f"{i}. {step}")
    return "\n".join(out) + "\n"


_MANUAL_MARKER = "<!-- HARDNESS:MANUAL-DECISIONS-BELOW"


def _preserve_manual_decisions(existing: Path) -> str:
    """Keep anything the user appended below the manual marker."""
    if not existing.exists():
        return ""
    try:
        text = existing.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    idx = text.find(_MANUAL_MARKER)
    if idx == -1:
        return ""
    after = text[idx:].split("-->", 1)
    return after[1].strip() if len(after) > 1 else ""


def write_agent_dir(model: ProjectModel, agent_dir: Path) -> dict:
    """Write the full .agent/ tree. Returns a manifest dict."""
    model.generated_at = model.generated_at or _now()
    model.engine_version = model.engine_version or __version__
    agent_dir.mkdir(parents=True, exist_ok=True)

    written: list[str] = []

    def emit(rel: str, content: str):
        _w(agent_dir / rel, content)
        written.append(rel)

    emit("architecture.md", _architecture_md(model))
    emit("glossary.md", _glossary_md(model))
    emit("constraints.md", _constraints_md(model))

    # decisions: preserve manual additions
    manual = _preserve_manual_decisions(agent_dir / "decisions.md")
    decisions_md = _decisions_md(model)
    if manual:
        decisions_md = decisions_md.rstrip() + "\n\n" + manual + "\n"
    emit("decisions.md", decisions_md)

    # modules
    for m in model.modules:
        emit(f"modules/{_slug(m.name)}.md", _module_md(model, m))
    # flows (ensure unique filenames)
    flow_slugs: dict[str, int] = {}
    for flow in model.flows:
        base = _slug(flow.name)
        n = flow_slugs.get(base, 0)
        flow_slugs[base] = n + 1
        fname = base if n == 0 else f"{base}-{n}"
        emit(f"flows/{fname}.flow.md", _flow_md(model, flow))

    # structured data
    emit("entities.json", json.dumps([vars(x) for x in model.entities],
                                     ensure_ascii=False, indent=2))
    emit("causal-graph.json", json.dumps({
        "nodes": [vars(n) for n in model.nodes],
        "edges": [vars(e) for e in model.edges],
    }, ensure_ascii=False, indent=2))

    # tasks dir placeholder
    (agent_dir / "tasks").mkdir(exist_ok=True)
    if not (agent_dir / "tasks" / "README.md").exists():
        _w(agent_dir / "tasks" / "README.md",
           "# Hardened Tasks\n\nEach incoming requirement is hardened into a "
           "`<id>.md` task spec here via `python scripts/wiki.py hardness harden`.\n")

    manifest = {
        "project": model.name,
        "root": model.root,
        "engine_version": model.engine_version,
        "generated_at": model.generated_at,
        "stats": model.stats,
        "artifacts": sorted(written),
        "provenance": "project-hardness (WEIPING_WIKI). Project-local facts; "
                      "do not sync raw facts to global memory.",
    }
    emit("index.json", json.dumps(manifest, ensure_ascii=False, indent=2))
    return manifest
